# 服务器配置项
[server]
address = "127.0.0.1"
port = 9090
timeout = 60

# 数据库配置项
[database]
driver = "mysql"
host = "127.0.0.1"
port = 3306
username = ""
password = ""
database = ""
maxConn = 2000
idleConn = 1000

# 通用配置
[common]

# 日志配置
[logging]
level = "DEBUG"
enableOutput = true
logFile = "./logs/server.log"

# Redis缓存配置
[cache]
host = "127.0.0.1"
port = 6379
password = ""
database = 0

# RabbitMQ配置
[queue]